### PR TITLE
broadcast tensors before execution

### LINKED ISSUE #4: Broadcast problem
I was testing the examples at https://www.tensorflow.org/api_docs/python/tf/einsum and noticed an interesting failure case (search for "Einsum will broadcast over axes covered by the ellipsis" on that page):

```py
import tensorflow as tf
import einsum
s = tf.random.normal(shape=[11, 1, 5, 3])
t = tf.random.normal(shape=[1, 7, 3, 2])
e =  tf.einsum('...ij,...jk->...ik', s, t)
print(e.shape)
e2 =  einsum.einsum('...ij,...jk->...ik', s.numpy(), t.numpy())
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 228, in einsum
    return einsum_execute(spec, list(tensors))
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 223, in einsum_execute
    return einsum_tensor_frompos(fn, spec.output.shape)
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 31, in einsum_tensor_frompos
    return einsum_tensor(recurse([], shape))
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in recurse
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in <listcomp>
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in recurse
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in <listcomp>
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in recurse
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in <listcomp>
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in recurse
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 29, in <listcomp>
    return [ recurse(pos + [i], remainder) for i in range(shape[0]) ]
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 26, in recurse
    return fn(*pos)
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 221, in fn
    return recurse(in_only_idxs)
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 218, in recurse
    acc += recurse(tail)
  File "/Users/shawn/ml/einsum/src/einsum/lib.py", line 210, in recurse
    prod *= tensor.item(*pos)
IndexError: index 1 is out of bounds for axis 1 with size 1
```

image

The example right above it works fine:

image

```py
import tensorflow as tf
import einsum
import numpy as np
s = tf.random.normal(shape=[11, 7, 5, 3])
t = tf.random.normal(shape=[11, 7, 3, 2])
e =  tf.einsum('...ij,...jk->...ik', s, t)
print(e.shape)
e2 = einsum.einsum('...ij,...jk->...ik', s.numpy(), t.numpy())
np.allclose(e, e2) # True
```

So the problem seems related to broadcasting axes covered by ellipses.

### PR DESCRIPTION
**Pull request by sorenlassen**
fixes #4

### CODE REVIEW

**Comment by shawwn** [comment]
Can we implement this without relying on numpy? The ultimate goal is to port this to C++, so although this works, it becomes hard to port.

**Comment by sorenlassen** [comment]
yeah, I don't love the fix, it was the quickest and dirtiest I could think of when I found the root cause :)

it's possible to implement without broadcasting the input tensors but will require more code (or something smart that I haven't come up with yet...)

let me take another pass

you're also most welcome to give it a shot, of course

**Comment by shawwn** [comment]
Oh, you’re right. Actually I think relying on numpy broadcast is ok. We support broadcasting in general in our compiler, so it shouldn’t be a problem.

I’m a bit curious whether there’s any corner cases for this… it sounds like only the ellipsis indices should be broadcast, not the whole tensor. But I also can’t think of anything offhand.

Broadcasting to the output shape is probably best, like you’re doing here. 👍

**Comment by sorenlassen** [comment]
everything broadcasts, see the last test I added with "ab" instead of ellipsis

except repeated indices within the same input operand, see https://github.com/sorenlassen/einsum-experiment/commit/d732e043a8320ec8e2b4b0851525e9a441be84aa

**Review by shawwn — APPROVED** [review]
Looks good to me!

**Comment by shawwn** [comment]
> everything broadcasts, see the last test I added with "ab" instead of ellipsis
> 
> except repeated indices within the same input operand, see [d732e04](https://github.com/sorenlassen/einsum-experiment/commit/d732e043a8320ec8e2b4b0851525e9a441be84aa)

Ah, I see! I guess tensorflow’s einsum is either different or (more likely) the docs don’t mention the broadcast behavior, or I missed it.

Thank you :)

**Pull request merged**
